# .appveyor.yml - AppVeyor settings for HamSandwich
version: '{build}'

# PR settings
skip_branch_with_pr: true
pull_requests:
    do_not_increment_build_number: true

image: Visual Studio 2019

# Build matrix
environment:
    matrix:
    -   MSVC: 1
    -   MSYSTEM: MINGW32
    -   APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
    -   MSVC_RELEASE: 1

for:
# Windows/MSYS2 build script
-   matrix:
        only:
            - MSYSTEM: MINGW32
    cache:
        - 'C:\msys64\var\cache\pacman\pkg'
    install:
        - set "PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%"
        - set "CHERE_INVOKING=1"
        - bash -lc './tools/build/install-deps.sh'
    build_script:
        - bash -lc 'make'

# Windows/MSVC build script
-   matrix:
        only:
            - MSVC: 1
    install:
        - powershell ./tools/msvc/install-dependencies.ps1
    before_build:
        - build\premake5.exe vs2019
    build_script:
        - msbuild build/msc-v142/HamSandwich.sln /p:Configuration=debug /p:Platform=Win32 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

# Windows/MSVC/release build script
-   matrix:
        only:
            - MSVC_RELEASE: 1
    branches:
        only:
            - master
    build_script:
        - powershell ./tools/msvc/build-binary-package.ps1
    artifacts:
        - path: ./build/HamSandwich-windows.zip
          name: HamSandwich.zip

# Linux build script
-   matrix:
        only:
            - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
    install:
        - sh: sudo DEBIAN_FRONTEND=noninteractive apt-get update
        - sh: ./tools/build/install-deps.sh
    build_script:
        - sh: make config=debug_x86_64

deploy:
# Windows/MSVC/Release deploy script
    -   provider: Environment
        name: HamSandwich release
        on:
            MSVC_RELEASE: 1
