# .appveyor.yml - AppVeyor settings for HamSandwich
version: '{build}'

# PR settings
skip_branch_with_pr: true
pull_requests:
    do_not_increment_build_number: true

image: Visual Studio 2019

# Build matrix
environment:
    matrix:
    #-   MSVC: 1
    #-   MSYSTEM: MINGW32
    -   MSVC_RELEASE: 1
    -   APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804

for:
# Windows/MSYS2 build script
-   matrix:
        only:
            - MSYSTEM: MINGW32
    cache:
        - 'C:\msys64\var\cache\pacman\pkg'
    install:
        - set "PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%"
        - set "CHERE_INVOKING=1"
        - bash -lc './tools/build/install-deps.sh'
    build_script:
        - bash -lc 'make'

# Windows/MSVC build script
-   matrix:
        only:
            - MSVC: 1
    install:
        - powershell ./tools/msvc/install-dependencies.ps1
    before_build:
        - build\premake5.exe vs2019
    build_script:
        - msbuild build/msc-v142/HamSandwich.sln /p:Configuration=debug /p:Platform=Win32 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

# Windows/MSVC/release build script
-   matrix:
        only:
            - MSVC_RELEASE: 1
    install:
        - powershell ./tools/msvc/install-butler.ps1
    build_script:
        - powershell ./tools/msvc/build-binary-package.ps1
    deploy_script:
        - ps: |
            if ($Env:APPVEYOR_REPO_BRANCH -eq "master" -and !$Env:APPVEYOR_PULL_REQUEST_NUMBER) {
                build/butler.exe push --if-changed build/pkgroot spacemaniac/hamsandwich:windows ("--userversion=" + (git rev-parse --short=10 HEAD))
            }

# Linux build script
-   matrix:
        only:
            - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
    install:
        - sh: sudo DEBIAN_FRONTEND=noninteractive apt-get update
        - sh: ./tools/build/install-deps.sh
        - sh: ./tools/itch/install-butler-linux.sh
    build_script:
        - sh: make config=release_x86_64
    before_deploy:
        - sh: |
            mkdir -p build/pkgroot
            cp build/gcc/release-x86_64/{supreme/supreme,mystic/mystic,loonyland/loonyland,loonyland2/loonyland2,sleepless/sleepless} build/pkgroot/
            cp tools/itch/linux.itch.toml build/pkgroot/.itch.toml
    deploy_script:
        - sh: test "$APPVEYOR_REPO_BRANCH" = "master" && test -z "$APPVEYOR_PULL_REQUEST_NUMBER" && build/butler push --if-changed build/pkgroot spacemaniac/hamsandwich:linux --userversion="$(git rev-parse --short=10 HEAD)"
