[[actions]]
name = "Dr. Lunatic Supreme With Cheese"
path = "supreme"

[[actions]]
name = "Kid Mystic"
path = "mystic"

[[actions]]
name = "Loonyland: Halloween Hill"
path = "loonyland"

[[actions]]
name = "Loonyland 2: Winter Woods"
path = "loonyland2"

[[actions]]
name = "Sleepless Hollow"
path = "sleepless"
