[[actions]]
name = "Dr. Lunatic Supreme With Cheese"
path = "supreme.exe"

[[actions]]
name = "Kid Mystic"
path = "mystic.exe"

[[actions]]
name = "Loonyland: Halloween Hill"
path = "loonyland.exe"

[[actions]]
name = "Loonyland 2: Winter Woods"
path = "loonyland2.exe"

[[actions]]
name = "Sleepless Hollow"
path = "sleepless.exe"

[[prereqs]]
name = "vcredist-2019-x86"
